on: [push]

name: CI

jobs:
  build_and_test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Install
      run: sudo apt install libxcb-composite0-dev

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - uses: actions/checkout@v2

    - uses: actions-rs/cargo@v1
      with:
        command: test
